language: python

python:
  - 3.4
  - 3.5
  - 3.6

addons:
  apt:
    packages:
      - lzop

install: pip install tox python-coveralls

script:
  - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)

after_success:
  - coveralls
